name: deploy

on:
  push:
    brunches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: vh360.timeweb.ru
          username: ck86039
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: .
          server-dir: /ci-cd/public_html/
